### ISSUE TITLE
Culture-aware enhancement

### ISSUE THREAD

**Issue by scriptingstudio** [jdhitsolutions/PSCalendar#29]
Hi, Jeff

I would like to suggest a couple of enhancements for `_getCalendar` function.
You have `$FirstDay` hardcoded.
My corrections to keep culture weekday order:
```powershell
Param (
    [datetime]$start = (Get-Date),
    [System.DayOfWeek]$FirstDay, # default is null
    [string[]]$highlightDates,
    [switch]$NoANSI
)
```
After line 12 or somewhere or even in `param` block
```powershell
if (-not $FirstDay) {$FirstDay = ([system.globalization.cultureinfo]::new((get-culture).name)).DateTimeFormat.FirstDayOfWeek}
# if (-not $FirstDay) {$FirstDay = $currCulture.DateTimeFormat.FirstDayOfWeek}
```
      
A calendar contains days of the previous and the next months. After line 166 I would insert a filter expression. This is optional but a calendar looks cleaner.
```powershell
if ($start.month -ne $theDay.month) {
    $theDay = $null
    $d = '  '
}
```

### UPDATE
Oh, I did not see $FirstDay in `Get-Calendar`. Just learned `_getCalendar`

**Comment by jdhitsolutions** [comment]
The `_getCalendar` command is a private helper function which is why it has a non-standard name. `Get-Calendar` is the command a user is supposed to run. The reason the helper function uses the first day of the week is because there is a .NET bug where the first day is sometimes incorrect, at least when testing across cultures. But this should have bearing on `Get-Calendar` .  

I don't have an issue with showing the leading or trailing days. But I can see where someone might like a cleaner look. Let me see what I can do to add a parameter.

**Comment by jdhitsolutions** [comment]
Are you running `Get-Calendar` from a console prompt? The ANSI commands don't work properly when using the PowerShell ISE. I am adding a new parameter.

![image](https://user-images.githubusercontent.com/12089920/156179094-90d99eb3-d2c8-4013-8cad-322dbaf19f7d.png)

**Comment by scriptingstudio** [comment]
Yes, from console. I dont use ISE at all.
And I am trying to understand what is wrong to my environment

**Comment by jdhitsolutions** [comment]
Run `Get-Host`, `Get-Calendar` and `Get-Calendar -noansi` and post screenshots.

**Comment by scriptingstudio** [comment]
I have found it.  :-)) That is my fault. I lost 2 variables - `$esc`  and `$PSCalendarConfiguration`
![image](https://user-images.githubusercontent.com/17237559/156186300-2841a5f6-0cbb-417c-ad14-f4ee8f07b367.png)

**Comment by jdhitsolutions** [comment]
That will do it. Did you manually delete the variables? I'm wondering if I need to add some protection to them.

**Comment by jdhitsolutions** [comment]
Actually, `$PSCalendarConfiguration` is in the module scope so you couldn't have removed it from the console. `$esc` should also be in the module scope, yet I can see it with `Get-Variable`. That puzzles me.

**Comment by jdhitsolutions** [comment]
I've pushed version 2.8.0 to the PowerShell gallery which updates `Get-Calendar`, 'Show-Calendar`, and `Get-NCalendar` with a `-MonthOnly` parameter.

**Comment by scriptingstudio** [comment]
`-MonthOnly` is good. But one more thing.
Paper calendars show "foreign" days dimmed, so I would suggest 2 modes:
- ansi coloring: "foreign" days - dimmed
- `-noansi`: no "foreign" days - it makes calendar cleaner

then `-MonthOnly` is almost useless

**Comment by jdhitsolutions** [comment]
I don't think I understand what you mean by `foreign` days.

**Comment by scriptingstudio** [comment]
I mean days not belonging to current month

**Comment by jdhitsolutions** [comment]
I understand now. But I might want all the days with no ANSI.

![image](https://user-images.githubusercontent.com/12089920/156201908-9896f6d8-c0de-49be-966f-c4c4ecb8499a.png)

Especially if I want to save this to a file, which is why `NoANSI` came about in the first place.

I can do this with v2.8.0

![image](https://user-images.githubusercontent.com/12089920/156202232-f61649c9-7490-45b7-8f02-4bbb422522b2.png)
![image](https://user-images.githubusercontent.com/12089920/156202418-5542bfbb-1817-473b-b5ba-7da059874b14.png)

Although using `NoAnsi`  makes highlighting dates irrelevant.  I think the current parameter options offer the most flexibility.  You can always use $PSDefaultParameterValues to set your defaults.

![image](https://user-images.githubusercontent.com/12089920/156203053-47d943a7-c391-4dae-87dd-33ddbbd4566f.png)

I'm want the command to be as flexible as possible. But if there is a use case I'm not considering,  please let me know.

**Comment by scriptingstudio** [comment]
Then, for flexibility I would suggest a parameter to display a calendar in different culture

**Comment by scriptingstudio** [comment]
> How often is someone really going to need to display a calendar in a different culture?

Agree. Not often.

I have added highlighting for weekend
```powershell
$PSCalendarConfiguration = @{
    Title      = "$esc[38;5;3m"
    DayOfWeek  = "$esc[1;4;36m"
    Today      = "$esc[38;5;3m"
    Highlight  = "$esc[92m"
    Weekend    = "$esc[38;5;1m"
}
#
$weekend = if ($fd -eq 0) {0,6} else {5,6} # after line 159
if ($NoANSI) {$value} # line 185
elseif ($k -in $weekend) {
    "{0}{1}{2}" -f $PScalendarConfiguration.Weekend, $value, "$esc[0m"
} else {$value}
```

![image](https://user-images.githubusercontent.com/17237559/156225243-33571f57-5411-4f63-a638-e35e08ab889d.png)

**Comment by jdhitsolutions** [comment]
Very nice. It looks like you have a version of this module that satisfies your requirements. If you want to try running a different culture, take a look at https://github.com/jdhitsolutions/PSScriptTools/blob/master/functions/Test-WithCulture.ps1.

**Comment by scriptingstudio** [comment]
`Test-WithCulture -Culture ([system.globalization.cultureinfo]::new('en-us')) -Scriptblock {Get-Calendar -MonthOnly}`
![image](https://user-images.githubusercontent.com/17237559/156232528-b456e9ad-f262-4139-be2b-cfde29ad5bfa.png)

**Comment by scriptingstudio** [comment]
Without `-Monthonly` or proper highlighting we have confusing information

![image](https://user-images.githubusercontent.com/17237559/156232986-1eb91da8-872d-43ba-9713-b87121b0321d.png)

**Comment by jdhitsolutions** [comment]
I'm thinking we have a different perspective on this topic.

![image](https://user-images.githubusercontent.com/12089920/156249236-1dcc2ab3-b395-495e-a6f2-4ea3105e8e96.png)

Personally, I don't have a problem with this result and don't find it confusing.

**Comment by jdhitsolutions** [comment]
I think we've resolved the original problem in this issue so I'll close this. We have separate open issues for the other topics.
